apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: {{name}}  
spec:
  schedule: {{schedule}}
  jobTemplate:         
    spec:
      parallelism: {{completions}}    
      completions: {{completions}}     
      template:
        spec:
          containers:
          - name: {{name}}
            image: docker-registry.default.svc:5000/{{project}}/base
            command: ["bash", "-c", ""]
            volumeMounts:        
            - mountPath: /opt/test
              name: data
            - mountPath: /.aws
              name: aws-conf
          volumes:
          - name: data
            emptyDir: {}
          - name: aws-conf
            persistentVolumeClaim:
              claimName: aws-conf
          restartPolicy: Never
