apiVersion: batch/v1
kind: Job
metadata:
  name: "{{name}}"
spec:
  parallelism: 1    
  completions: 1    
  template:         
    metadata:
      name: "{{name}}"
    spec:
      containers:
      - name: "{{name}}"
        image: docker-registry.default.svc:5000/{{project}}/base
        command: ["bash", "-c", ""]
        volumeMounts:        
        - mountPath: /opt/test
          name: data
        - mountPath: /.aws
          name: aws-conf
      volumes:
      - name: data
        emptyDir: {}
      - name: aws-conf
        persistentVolumeClaim:
          claimName: aws-conf
      restartPolicy: OnFailure