---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: base
  labels:
    app: base
spec:
  template:
    metadata:
      labels:
        app: base
    spec:
      containers:
      - name: base
        image: base
        volumeMounts:
          - mountPath: /.aws
            name: aws-conf
      volumes:
      - name: aws-conf
        persistentVolumeClaim:
          claimName: aws-conf
  replicas: 1
          