---
apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: grafana
  labels:
    app: grafana
spec:
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana
        ports:                
        - name: api
          containerPort: 3000
        volumeMounts:
        - mountPath: /usr/share/grafana/data
          name: data        
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: grafana      
  replicas: 1
  triggers:
    - type: ConfigChange
    - imageChangeParams:
        automatic: true
        containerNames:
          - grafana
        from:
          kind: ImageStreamTag
          name: 'grafana:latest'
      type: ImageChange
          